version: "3"
services:
  app:
    build: .
    depends_on:
      - ptais-db
    ports:
      - "3000:3000"
    networks:
      - app-network
  ptais-db:
    image: postgres
    container_name: ptais-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=-V4c3x2z1
      - POSTGRES_DB=mvdb
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
