version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: -V4c3x2z1
      POSTGRES_DB: moviedb
  api:
    build: .
    container_name: api
    ports:
      - '3005:3005'
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: -V4c3x2z1
      DATABASE_NAME: moviedb
